import os

SELENIUM_FIREFOX_URL = os.environ["SELENIUM_FIREFOX_URL"]
SELENIUM_CHROME_URL = os.environ["SELENIUM_CHROME_URL"]
WEB_HTTP_PUBLIC_URL = os.environ["WEB_HTTP_PUBLIC_URL"]
WEB_HTTP_LOCAL_URL = os.environ["WEB_HTTP_LOCAL_URL"]
WEB_CONTROL_URL = os.environ["WEB_CONTROL_URL"]
WEB_HTTPS_PUBLIC_URL = os.environ["WEB_HTTPS_PUBLIC_URL"]
JSHELTER_FIREFOX_PATH = os.environ.get("JSHELTER_FIREFOX_PATH")
